[package]
name = "codingfetch"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
tabled = { version = "0.13.0", features = ["macros"] }
regex = "1.9.1"